### ISSUE TITLE
go get fails with undefined and too many args errors

### ISSUE THREAD

**Issue by jbayer** [pivotal-cf-experimental/lattice-cli#11]
$ go get -u github.com/pivotal-cf-experimental/lattice-cli/ltc
# github.com/pivotal-cf-experimental/lattice-cli/app_runner/docker_metadata_fetcher
../../go/src/github.com/pivotal-cf-experimental/lattice-cli/app_runner/docker_metadata_fetcher/docker_metadata_fetcher.go:28: undefined: registry.ResolveRepositoryName
../../go/src/github.com/pivotal-cf-experimental/lattice-cli/app_runner/docker_metadata_fetcher/docker_metadata_fetcher.go:33: too many arguments in call to registry.NewEndpoint

**Comment by onsi** [comment]
Sounds like Docker changed their API on us?  This sort of thing is going to happen periodically.  Switching to prebuilt binaries will obviously help.

**Comment by cf-buildpacks-eng** [comment]
In cloudrocker (née focker), Colin Humphreys built in a sanity check that
complains if the Docker client and server are out of sync, because of the
pace at which they change things.

**Comment by onsi** [comment]
that still won't solve the `go get` flow

we've decided to move away from `go get` as the primary distribution mechanism in favor of uploading platform-specific binaries.  We'll make these easily `wget`able and will update the doc.

**Comment by drnic** [comment]
The go universe needs a tool chain for creating/distributing binaries; and end users getting the platform version they need.


CF plugins ecosystem will also need something like this too (from CLI inception yesterday)

**Comment by jbayer** [comment]
this is a work-around until this is fixed

```
cd $GOPATH/src/github.com/docker/docker
git checkout 7b7af6dbaeadb86c018a877af15c662786bc90c1
get github.com/pivotal-cf-experimental/lattice-cli/ltc
```

**Comment by davidwadden** [comment]
both of the above-discussed strategies are now available -- we provide binaries for download and vendor the dependencies using godep -- docker specifically has unstable code in their master that prevents us from simply go getting ltc.

detailed instructions are available at:   https://github.com/cloudfoundry-incubator/lattice/blob/develop/ltc/README.md
