### ISSUE TITLE
ltc visualize help should show '1s' as example instead of '0'

### ISSUE THREAD

**Issue by jbayer** [pivotal-cf-experimental/lattice-cli#12]
help currently has

```
OPTIONS:
   --rate, -r '0'	The rate in seconds at which to refresh the visualization.
```
without having the time unit it is confusing and hard to deduce you need the '1s'. e.g. this works for me `ltc visualize -r 1s` and this does not `ltc visualize -r '1'`

**Comment by dajulia3** [comment]
The values next to the flags also represent the default value, so setting this would actually change behavior. We addressed this with more detailed usage text. To make the '0' into a '0s' would have required a PR to codegangsta/cli, which at this point isn't a priority for us.

**Comment by jbayer** [comment]
I could not figure out the syntax when I first read the help. I thought this was broken for over a day. One alternative is that we could put an example using '1s' in the description part of the help output that wouldn't violate the example is the default convention.

**Comment by onsi** [comment]
this is now fixed - there are example values in the doc
