### ISSUE TITLE
Ensure `ltc target` works with receptors without basic auth

### ISSUE THREAD

**Issue by drnic** [pivotal-cf-experimental/lattice-cli#8]
See https://github.com/pivotal-cf-experimental/lattice-cli/commit/ff19daf9a6cd5aa474bf4d96dc0775f041cb10b7#diff-c6388d94c49e8d54223d0c35252c27a3L65 & inline comments

If I provide "" values, it doesn't work.

```
$ ltc target 10.0.2.15.xip.io
Username: 
Password: 
Could not verify target.
```

**Comment by matthewmcnew** [comment]
The CLI is now updated to only prompt for Username/Password if connecting to the Receptor returns an Unauthorized Error. If the receptor returns an error other than Unauthorized, it alerts the user and does not prompt for credentials.

Let us know if you have any additional problems.  

@davidwadden / @matthewmcnew

**Comment by drnic** [comment]
Thanks!
